name: exson_bank
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.0

  firebase_core: ^2.30.1

  firebase_auth: ^4.19.4
  google_sign_in: ^6.2.1
  flutter_local_notifications: ^17.0.0

  permission_handler: ^11.3.1

  local_auth: ^2.2.0

  image_picker: ^1.0.7
  path_provider: ^2.0.0
  flutter_timezone: ^1.0.4
  firebase_messaging: ^14.9.1
  firebase_storage: ^11.7.4
  cloud_firestore: ^4.17.2
  shared_preferences: ^2.2.2
  flutter_bloc: ^8.1.5
  bloc_concurrency: ^0.2.5
  equatable: ^2.0.5
  connectivity_plus: ^6.0.3
  change_app_package_name: ^1.1.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9


  fluttertoast: ^8.2.5
  adaptive_theme: ^3.6.0
  pinput: ^4.0.0

  mask_text_input_formatter: ^2.9.0
  carousel_slider: ^4.2.1
  intl: ^0.19.0
  rxdart: ^0.27.0





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Black.otf
        - asset: assets/fonts/inter/Inter-Bold.otf
        - asset: assets/fonts/inter/Inter-Italic.otf
        - asset: assets/fonts/inter/Inter-Light.otf
        - asset: assets/fonts/inter/Inter-Medium.otf
        - asset: assets/fonts/inter/Inter-Regular.otf
        - asset: assets/fonts/inter/Inter-SemiBold.otf

        - asset: assets/fonts/rubik/Rubik-Black.ttf
        - asset: assets/fonts/rubik/Rubik-Bold.ttf
        - asset: assets/fonts/rubik/Rubik-Italic.ttf
        - asset: assets/fonts/rubik/Rubik-Light.ttf
        - asset: assets/fonts/rubik/Rubik-Medium.ttf
        - asset: assets/fonts/rubik/Rubik-Regular.ttf
        - asset: assets/fonts/rubik/Rubik-SemiBold.ttf